### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by chrisnatali** [chrisnatali/mapview-poc#1]
- [x] Set view info in cookie
- [x] cache-bust on server side for dynamic tilesets
- [x] validation of posted layers/views (can js be validated client-side?)

**Comment by chrisnatali** [comment]
Cache config on server-side involves either modifying [tilemill source](https://github.com/mapbox/tilemill/blob/8044976d3d0a1b78de663c24009239994db76b7b/servers/Tile.bones#L161) or wrapping tilemill in a proxy that globally sets headers.  Too much to maintain for now, so leaving the client-side hack in place.

**Comment by chrisnatali** [comment]
Kicking validation down the road...edit layers/views in git repo (data dir) for now
